# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: MontessoriAttiva - Pavia
email: montessoriattivapavia@gmail.com
alt_email: montessoriattivapavia[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  MontessoriAttiva – Pavia è un gruppo di genitori, educatori e insegnanti 
  che hanno maturato interesse per la scuola di metodo Montessori 
  e, più in generale, per il pensiero pedagogico di Maria Montessori.
  Il nostro obiettivo è questo: portare il Metodo nelle scuole del Pavese...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.montessoriattiva-pavia.it" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
# facebook_groupname: MontessoriAttiva - Pavia
facebook_groupname: Pagina Facebook
facebook_pagename: MontessoriAttivaPavia

# Build settings
markdown: kramdown
timezone: Europe/Rome

exclude: [vendor]
